spring:
  kafka:
    consumer:
      group-id: rent-payment
      topic-name: rm_mails
    bootstrap-servers: 161.97.69.205:9094, 161.97.69.205:9095, 161.97.69.205:9096
    streams:
      application-id: rent-payment
    # bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://161.97.69.205:5432/cards
    username: remas
    password: Pass@word1
    driver-class-name: org.postgresql.Driver  
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 161.97.69.205
      port: 6379
      # password: password
      database: 11
      ttl: 300000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

rsa:
  private-key: classpath:certs/private_key.pem
  public-key: classpath:certs/public_key.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /cards-app/v3/api-docs
    enabled: true